# Generated by Django 4.1 on 2022-09-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premio',
            name='administrador',
        ),
    ]
