# Generated by Django 4.1 on 2022-09-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(default='', max_length=12, verbose_name='CEP'),
            preserve_default=False,
        ),
    ]
