# Generated by Django 4.1 on 2022-09-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
